package Controller;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import Model.Comment;
import Model.Database;
import Model.Post;
import View.Alert;


//retrieves all comments for a specific post and counts the number of comments
public class ReadPostComments {
	
	//keeps track of comments
	private int commentsCounter;
	
	//list of comments retrieved from database
	private ArrayList<Comment> comments;
	
	public ReadPostComments(Post p, Database database) {
		commentsCounter = 0;
		
		//retrieve the comments for the given post and populates the comments list with the retrieved data
		String select = "SELECT * FROM `comments` WHERE `Post` = "+p.getID()+" ;";
		ArrayList<Integer> usersIDs = new ArrayList<>();
		comments = new ArrayList<>();
	try {
		ResultSet rs = database.getStatement().executeQuery(select);
		while (rs.next()) {
			commentsCounter++;
			Comment c = new Comment();
			c.setID(rs.getInt("ID"));
			c.setContent(rs.getString("Content"));
			usersIDs.add(rs.getInt("User"));
			c.setDateTimeFromString(rs.getString("DateTime"));
			comments.add(c);
		 }
		for(int i=0;i<comments.size();i++) {
			comments.get(i).setUser(new ReadUserByID(usersIDs.get(i), database)
					.getUser());
		}
	  } catch (SQLException e) {
		new Alert(e.getMessage(), null);
	  }
	}
	
	
	//returns the number of comments retrieved by the constructor
	public int getCommentsCount() {
		return commentsCounter;
	}
	
	
	//method returns the list of comments generated by the constructor
	public ArrayList<Comment> getComments() {
		return comments;
	}

	
}
